### ISSUE TITLE
Error 405 - Method Not Allowed

### ISSUE THREAD

**Issue by idkjs** [jahewson/elm-graphql-demo#3]
When i run 'elm graphql', i get 'Error 405 - Method Not Allowed'. I cant find any docs on this error. Any ideas?

Thanks.

**Comment by jahewson** [comment]
Try updating `graphql-starwars` from git and rebuilding it. I've made some changes which might affect this.

**Comment by jahewson** [comment]
I've added some more detailed errors in `elm-graphql` v1.0.6 too.
